# Generated by Django 4.2.12 on 2025-05-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('code', models.TextField(blank=True, null=True, unique=True)),
                ('unit_price', models.FloatField(default=0)),
                ('inventory', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(blank=True, to='storage.category')),
                ('color', models.ManyToManyField(blank=True, to='storage.color')),
            ],
        ),
    ]
