# Generated by Django 4.2.12 on 2025-05-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Size',
        ),
        migrations.AddField(
            model_name='storage',
            name='size',
            field=models.ManyToManyField(blank=True, to='storage.size'),
        ),
        migrations.RemoveField(
            model_name='storage',
            name='category',
        ),
        migrations.AddField(
            model_name='storage',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
