# Generated by Django 4.2.12 on 2025-05-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_rename_category_size_storage_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='color_storage', to='storage.color'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='size_storage', to='storage.size'),
        ),
    ]
